### ISSUE TITLE
Compressor causing excessive render updates (2.2.26)

### ISSUE THREAD

**Issue by L-Clouds** [p455w0rd/p455w0rd-s-Things#34] opened 2017-10-07 11:06 UTC
Well, I was wondering why my chunk render times skyrocketed recently...  I'd placed and powered a Compressor.

[Sampler](https://forum.industrial-craft.net/thread/10820-wip-1-7-10-fastcraft-1-23-note-all-posts-of-new-members-need-to-be-approved-firs/) with the command _/csampler renderupdates show --cross_ revealed that the Compressor is renderupdate...ing?.. continually, every tick or frame or however often render updates happen, while receiving power or while operating.  Sitting by itself, it's fine, but even if its internal buffer is full, if it's connected to power, it's updating.

This is true for direct placement next to an EnderIO capacitor or a Mekanism energy cube, or when powered by a Solar Flux cable or EnderIO cable.  Oddly a Mekanism cable seems to stop providing power once the Compressor's internal buffer is full but of course render updates resume if it needs charging again.

I saw this mentioned in #10 and #12 but both are closed and the issue is present in your latest release.  Tested in Project Ozone Lite 1.2.0 but with p455w0rd's Things updated to 2.2.26

FWIW, turning off smooth lighting AND Forge Light Pipeline brought my FPS back up but probably just because those settings made render updates fast enough that it could keep up with what the Compressor was doing.

**Comment by p455w0rd** [comment] 2017-10-07 16:31
I'll work with someone and see if we can't get some efficiency out of the rendering...the issue in the past has usually been the the people who create the issue simple stop responding in situations where I am unable to reproduce these results myself...I do have a really good idea as to what's going on and at least how to begin fixing this. I'm just not so knowledgable in this area, but I'm always willing to learn. If you are knowledgable in the areas of rendering, and are willing to help, then by all means, please join my discord at http://p455w0rd.net/discord and I will work with you :). Thanks for the report!

**Comment by L-Clouds** [comment] 2017-10-08 07:11
Mmh, well, on the minus side, I'm at best beginner-level with Java, I've got almost no knowledge of the code internals of Minecraft, of Forge or its API, or of CoFHLib/CodeChickenLib, I've not got an IDE nor Gradle set up, and I've never used Discord.

On the plus side, I've got a good mind for engineering and I'm pretty good at bug-hunting.  And I'm not afraid to edit a few opcodes to test some different logic.

On the minus side, the code is not in this repo, and around the line `state.func_177230_c().func_180650_b(func_145831_w(), func_174877_v(), state, func_145831_w().field_73012_v);` I realized I won't be able to follow the decompiled version...
_[edit] I found the source.  Looking around..._

Besides, I'd guess it's not rendering in a graphical sense, per se, that's at issue.  It's that something is making Minecraft re-compute what the block looks like way too often.

**Comment by L-Clouds** [comment] 2017-10-08 10:39
Well, I think I'm in over my head here.  I don't know what influences Minecraft to re-render a chunk, and I don't know what would be alternative approaches.  I tried running Sampler to get VisualVM .nps files but they seemed unilluminating except for showing that indeed the render pipeline was getting used more.

Here's a reproducible scenario, in the context of POLite 1.2.0:
- Make a creative superflat world with no structures and just bedrock.  Super simple.
- In a chunk, build a lot of Ex Nihilo sieves with meshes, like an 8x8 square of them.  They're just a good, expensive block to re-render and they do nothing by themselves.
- Put down a creative infinite energy source, maybe the Extra Utilities 2 one.  Put down a low-tier cable so power transfers kind of slowly.  Put a Compressor powered by that cable.  FPS should tank.  _(If not, it might be because you have B:alwaysSetupTerrainOffThread=true in forge.cfg in which case instead of tanking FPS, it will give you block render update lag.  It's more dramatic with B:alwaysSetupTerrainOffThread=false)_
- Break the cable.  FPS returns to normal.
- Try it with other machines.  Even stuff like the Mekanism Energy Cells or EnderIO Capacitors, which change their appearance depending on their stored charge, don't create any problems.

**Comment by p455w0rd** [comment] 2017-10-18 14:07
I have FINALLY gotten around to working on this :D

**Comment by L-Clouds** [comment] 2017-10-19 10:59
Sorry, cannot confirm.
[https://imgur.com/a/d3kVl](https://imgur.com/a/d3kVl)
Check the FPS.  In the background, those are sieves in the same chunk.
p455w0rdsthings-1.10.2-2.2.27 off of CurseForge just now, put in POLite 1.2.0

**Comment by p455w0rd** [comment] 2017-10-19 11:05
ok..let me add ex-nihilo to my dev env and test specifically with that mod

**Comment by p455w0rd** [comment] 2017-10-19 12:20
![](http://p455w0rd.net/u/08.17.43-19.10.17.png)
![](http://p455w0rd.net/u/08.19.32-19.10.17.png)

**Comment by p455w0rd** [comment] 2017-10-19 12:20
maybe it's that specific cable? at any rate..it's mod interaction at some point..i've done what I can on my end..this is fixed on my end

**Comment by p455w0rd** [comment] 2017-10-19 12:23
seriously..when I uncap my framerate:
![](http://p455w0rd.net/u/08.21.41-19.10.17.png)
and I by no means have a beast machine..i7-4790K,16GB DDR3, and 4GB AMD R7 370 GPU

**Comment by L-Clouds** [comment] 2017-10-20 00:15
And this was with alwaysSetupTerrainOffThread=false in forge.cfg?  Because otherwise, it creates block lag but preserves FPS.

OK, hang on, I'll try to make a minimal instance.  (I'd tried to before with Twitch but it was weirdly problematic and wouldn't let me break blocks, at all.)

**Comment by L-Clouds** [comment] 2017-10-20 00:54
Set up an instance with:
Forge 2511
CodeChickenLib-1.10.2-2.5.9.283-universal
EnderCore-1.10.2-0.4.1.66-beta
EnderIO-1.10.2-3.1.193
exnihiloadscensio-1.10.2-0.1.20
p455w0rdslib-1.10.2-1.0.30
p455w0rdsthings-1.10.2-2.2.27

Here's a zip with config, options, and save.
[p455.zip](https://github.com/p455w0rd/p455w0rd-s-Things/files/1400450/p455.zip)
[https://imgur.com/a/fa7Kv](https://imgur.com/a/fa7Kv)

I still had that can't-break-blocks problem but there was some _interesting_ stuff in the log about that.  That'd be a separate issue though.

**Comment by p455w0rd** [comment] 2017-10-20 00:56
i thought this was just on my end as far as the blocks not breaking..def another bug...the FPS..what are you PC specs? you HAVE to have a potato..i mean my pc is basically trash by today's standards and I experience no FPS hit..please consider this issue dealt with..the block breaking thing..that is def a new issue

**Comment by L-Clouds** [comment] 2017-10-20 01:02
i5-3320M @ 2.6GHz, 8GB RAM, SanDisk SSDs, NVIDIA NVS 5400M w/1GB (laptop of course)

And I'm about to test but I think you have a problem when Iron Chests isn't present:
[Log snippet of an error when I tried to break a block](https://gist.github.com/L-Clouds/3c3723dda2bae1968f34ff63d16eb893)

**Comment by p455w0rd** [comment] 2017-10-20 01:06
yup! that's a diff issue..I definitely appreciate you pointing this out! ..your frame lag is due to your machine though..nothing I can do there short of buying you a new PC unfortunately :(

**Comment by L-Clouds** [comment] 2017-10-20 01:09
The point, though, is other machines like those from EnderIO or Mekanism or Thermal Expansion don't cause any FPS drop in the same situation.  So, there MUST be something that can be improved, especially since it has to do with making a chunk re-render (there's very little FPS hit if there isn't something else complicated in the chunk) and not with the compressor block's own graphics.

**Comment by p455w0rd** [comment] 2017-10-20 01:14
i'll talk with caz about removing it...i'm done wasting time on it..sorry you've had this experience

**Comment by L-Clouds** [comment] 2017-10-20 01:16
Aw, I'd rather see it get solved.  I'd learn something from it, too.  It's your choice, though.  Thanks for putting up with me!

**Comment by p455w0rd** [comment] 2017-10-20 01:22
i have done literally everything that cane be done...do my screenshots not speak for themselves? 600+FPS with a setup identical to yours...what more do i have to do to prove this to you? none of the other machines you mentioned have the GL rendering mine does..if it is chunk updates...please refer to my last screenshot..unless you're running an old version..when the compressor isn't running, you shouldn't have ANY chunk updates from my tile entity...i will look over code and even rebuild just in case i got something mixed up,..but on my end..the problem is definitely solved

**Comment by p455w0rd** [comment] 2017-10-22 22:48
so i decided to actually put some time into this and figure it out :D hoping to have a fix soon :)

**Comment by p455w0rd** [comment] 2017-10-23 06:45
please let me know if there is any noticeable improvement

**Comment by L-Clouds** [comment] 2017-10-23 13:00
Yeah!  There is.  It's pretty much normal now. :)  Performance-wise it looks good?  I noticed a side effect of whatever you changed: the stored RF bar doesn't move/display new values while it's charging until the Compressor is given work to do, although The One Probe shows its actual stored RF the whole time.

**Comment by p455w0rd** [comment] 2017-10-23 13:58
ah...I'll make an issue and look into that in a future update, thanks for helping :)

**Closed as completed by p455w0rd** 2017-10-23 13:58 UTC
Labels: bug, next update
